//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.SodiQubeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityProcesedDetail
    {
        public short SodimatId { get; set; }
        public short CycleId { get; set; }
        public string MachineCode { get; set; }
        public string Product { get; set; }
        public Nullable<float> Peso { get; set; }
        public Nullable<float> Tiro { get; set; }
        public Nullable<float> Diametro { get; set; }
        public Nullable<byte> Turno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
