//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.SodiQubeDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SodiQubeDbEntities : DbContext
    {
        public SodiQubeDbEntities()
            : base("name=SodiQubeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<QualityStat> QualityStats { get; set; }
        public virtual DbSet<QualityTest> QualityTests { get; set; }
        public virtual DbSet<SubType> SubTypes { get; set; }
        public virtual DbSet<TR_Historial> TR_Historial { get; set; }
        public virtual DbSet<TR_QualityTestsSummary> TR_QualityTestsSummary { get; set; }
        public virtual DbSet<Turno> Turnoes { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<QualityProcesed> QualityProceseds { get; set; }
        public virtual DbSet<QualityProcesedDetail> QualityProcesedDetails { get; set; }
        public virtual DbSet<V_ParametrosProductos> V_ParametrosProductos { get; set; }
        public virtual DbSet<V_ProductosNotificados> V_ProductosNotificados { get; set; }
        public virtual DbSet<V_QualityProcesed> V_QualityProcesed { get; set; }
        public virtual DbSet<V_QualitystatsLast3moths> V_QualitystatsLast3moths { get; set; }
        public virtual DbSet<V_QualitytestLast3moths> V_QualitytestLast3moths { get; set; }
        public virtual DbSet<V_QualityTestsLast5Months> V_QualityTestsLast5Months { get; set; }
        public virtual DbSet<V_QualityTestsLast6Months> V_QualityTestsLast6Months { get; set; }
        public virtual DbSet<V_ReporteDatosIndividuales> V_ReporteDatosIndividuales { get; set; }
        public virtual DbSet<V_ReporteMuestras> V_ReporteMuestras { get; set; }
    
        public virtual int InsertarNuevosRegistros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarNuevosRegistros");
        }
    
        public virtual int InsertarRegistrosVerificados_OLD_()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertarRegistrosVerificados_OLD_");
        }
    
        public virtual int VerificarLimiteInferiorDiametro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarLimiteInferiorDiametro");
        }
    
        public virtual int VerificarLimiteInferiorPeso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarLimiteInferiorPeso");
        }
    
        public virtual int VerificarLimiteInferiorTiro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarLimiteInferiorTiro");
        }
    
        public virtual int VerificarLimiteSuperiorDiametro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarLimiteSuperiorDiametro");
        }
    
        public virtual int VerificarLimiteSuperiorPeso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarLimiteSuperiorPeso");
        }
    
        public virtual int VerificarLimiteSuperiorTiro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarLimiteSuperiorTiro");
        }
    
        public virtual int VerificarTiroDatosIndividuales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VerificarTiroDatosIndividuales");
        }
    }
}
