//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.SodiQubeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_QualityTestsSummary
    {
        public short CycleId { get; set; }
        public string MachineCode { get; set; }
        public string Product { get; set; }
        public short SodimatId { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Tiro { get; set; }
        public Nullable<double> Diametro { get; set; }
        public Nullable<byte> Turno { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Fecha2 { get; set; }
        public int ID { get; set; }
        public Nullable<bool> notificadoPeso { get; set; }
        public Nullable<bool> notificadoDiametro { get; set; }
        public Nullable<System.DateTime> fechaNotificacionPeso { get; set; }
        public Nullable<System.DateTime> fechaNotificacionDiametro { get; set; }
        public Nullable<bool> notificadoTiro { get; set; }
        public Nullable<System.DateTime> fechaNotificacionTiro { get; set; }
        public string correoNotificado { get; set; }
        public string comentarioNotificacionTiro { get; set; }
        public string comentarioNotificacionDiametro { get; set; }
        public string comentarioNotificacionPeso { get; set; }
        public Nullable<double> LciTiro { get; set; }
        public Nullable<double> LcsTiro { get; set; }
        public Nullable<double> TargetTiro { get; set; }
        public Nullable<double> LciPeso { get; set; }
        public Nullable<double> LcsPeso { get; set; }
        public Nullable<double> TargetPeso { get; set; }
        public Nullable<double> LeiPeso { get; set; }
        public Nullable<double> LesPeso { get; set; }
        public Nullable<double> LciDiametro { get; set; }
        public Nullable<double> LcsDiametro { get; set; }
        public Nullable<double> TargetDiametro { get; set; }
        public Nullable<double> LeiDiametro { get; set; }
        public Nullable<double> LesDiametro { get; set; }
    }
}
