//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.SodiQubeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ParametrosProductos
    {
        public string Product_ID { get; set; }
        public string Filler_Name { get; set; }
        public string Type_ID { get; set; }
        public string Subtype_ID { get; set; }
        public string Parameter_ID { get; set; }
        public string Parameter_Description { get; set; }
        public bool Display { get; set; }
        public decimal Value { get; set; }
    }
}
