//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.SodiQubeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductosNotificados
    {
        public System.DateTime Fecha { get; set; }
        public Nullable<byte> Turno { get; set; }
        public short CycleId { get; set; }
        public string Producto { get; set; }
        public string Máquina { get; set; }
        public short SodiQube { get; set; }
        public Nullable<double> Diametro { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Tiro { get; set; }
        public string Notificación_de_Tiro { get; set; }
    }
}
