//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.SodiQubeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ReporteDatosIndividuales
    {
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Semana { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public System.DateTime Fecha_y_hora { get; set; }
        public Nullable<byte> Turno { get; set; }
        public short No__Sodiqube { get; set; }
        public string Producto { get; set; }
        public string Máquina { get; set; }
        public Nullable<float> Diámetro { get; set; }
        public string Notificación_diámetro { get; set; }
        public Nullable<float> Peso { get; set; }
        public string Notificación_de_peso { get; set; }
        public Nullable<float> Tiro { get; set; }
        public string Notificación_de_tiro { get; set; }
    }
}
