//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bandeja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bandeja()
        {
            this.EstatusBandejas = new HashSet<EstatusBandeja>();
        }
    
        public string idBandeja { get; set; }
        public int secuenciaInicial { get; set; }
        public int secuenciaFinal { get; set; }
        public bool procesarSap { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string usuarioRegistro { get; set; }
        public bool estatusVigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatusBandeja> EstatusBandejas { get; set; }
    }
}
