//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionInicialControlSalida
    {
        public int Id { get; set; }
        public string IdEquipo { get; set; }
        public string IdProducto { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public int Turno { get; set; }
        public double CantidadConsumoPendiente { get; set; }
        public string Unidad { get; set; }
        public Nullable<System.DateTime> FechaLectura { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool Estatus { get; set; }
    }
}
