//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionSincronizacionTabla
    {
        public int id { get; set; }
        public string nombreTabla { get; set; }
        public bool procesarSap { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string usuarioRegistro { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuarioModificacion { get; set; }
    }
}
