//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumo
    {
        public string IdProceso { get; set; }
        public string Centro { get; set; }
        public string IdEquipo { get; set; }
        public string IdTiempo { get; set; }
        public string IdProducto { get; set; }
        public string VersionFabricacion { get; set; }
        public int Secuencia { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public int Turno { get; set; }
        public string IdMaterial { get; set; }
        public string Usuario { get; set; }
        public string IdSubEquipo { get; set; }
        public string Lote { get; set; }
        public double Cantidad { get; set; }
        public string Unidad { get; set; }
        public int NumeroCaja { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaSincronizacion { get; set; }
        public string IdBandeja { get; set; }
        public string IdEquipoOrigenMaterial { get; set; }
        public Nullable<int> SecuenciaSalida { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string BatchId { get; set; }
        public Nullable<bool> EstadoSalidaNotificacion { get; set; }
        public bool Sync { get; set; }
        public Nullable<System.DateTime> FechaCargaErp { get; set; }
    }
}
