//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstatusBandeja
    {
        public string idBandeja { get; set; }
        public int secuenciaBandeja { get; set; }
        public string estatus { get; set; }
        public string idEquipoLlenado { get; set; }
        public string idProceso { get; set; }
        public string idTiempo { get; set; }
        public string idMaterial { get; set; }
        public string versionFabricacion { get; set; }
        public Nullable<System.DateTime> fechaLlenada { get; set; }
        public Nullable<System.TimeSpan> horaLlenada { get; set; }
        public string usuarioLlenada { get; set; }
        public int secuenciaSalida { get; set; }
        public string batchId { get; set; }
        public double cantidad { get; set; }
        public string UMP { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public System.TimeSpan horaRegistro { get; set; }
        public Nullable<System.DateTime> fechaVaciada { get; set; }
        public Nullable<System.TimeSpan> horaVaciada { get; set; }
        public string idEquipoVaciado { get; set; }
        public string usuarioVaciada { get; set; }
        public string formaVaciada { get; set; }
    
        public virtual Bandeja Bandeja { get; set; }
    }
}
