//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialReimpresionEtiqueta
    {
        public int ID { get; set; }
        public string IdEquipo { get; set; }
        public int SecuenciaEtiqueta { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public int Turno { get; set; }
        public string Empaque { get; set; }
        public string AlmFiller { get; set; }
        public string UsuarioReimpresion { get; set; }
        public System.DateTime FechaReimpresion { get; set; }
        public bool Estatus { get; set; }
        public int IdMotivoReimpresion { get; set; }
    }
}
