//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MezclasProduccion
    {
        public string Idproceso { get; set; }
        public string Idequipo { get; set; }
        public int SecuenciaEntrada { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public int SecuenciaSalida { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaLlenada { get; set; }
        public System.DateTime fechaCarga { get; set; }
        public bool Sync { get; set; }
        public Nullable<System.DateTime> FechaCargaErp { get; set; }
    }
}
