//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoTipoAlmacenamiento
    {
        public int id { get; set; }
        public int idTipoProductoTerminado { get; set; }
        public int idTipoAlmacenamiento { get; set; }
        public string identificador { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public Nullable<System.TimeSpan> horaRegistro { get; set; }
        public string usuarioRegistro { get; set; }
        public string usuarioModificacion { get; set; }
        public string fechaModificacion { get; set; }
        public Nullable<System.TimeSpan> HoraModificacion { get; set; }
        public bool estatus { get; set; }
    
        public virtual TipoProductoTerminado TipoProductoTerminado { get; set; }
        public virtual TipoAlmacenamientoProducto TipoAlmacenamientoProducto { get; set; }
    }
}
