//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiempoBandeja
    {
        public int Id { get; set; }
        public string idProceso { get; set; }
        public string idTiempo { get; set; }
        public string idBandeja { get; set; }
        public double cantidad { get; set; }
        public string unidad { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    }
}
