//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traza
    {
        public string IdProceso { get; set; }
        public string IdTiempo { get; set; }
        public int IdRegistro { get; set; }
        public int AnoEjercicio { get; set; }
        public string IdEquipo { get; set; }
        public string Centro { get; set; }
        public string IdProducto { get; set; }
        public string VersionFabricacion { get; set; }
        public string NumeroLote { get; set; }
        public string LoteManufactura { get; set; }
        public int SecuenciaSalida { get; set; }
        public System.DateTime FechaProduccion { get; set; }
        public int Turno { get; set; }
        public string BatchId { get; set; }
        public string IdBandeja { get; set; }
        public string IdEmpaque { get; set; }
        public Nullable<int> SecuenciaEmpaque { get; set; }
        public double CantidadPedido { get; set; }
        public string UnidadMedidaPedido { get; set; }
        public double Peso { get; set; }
        public bool EstatusBandeja { get; set; }
        public string DocumentoMaterial { get; set; }
        public Nullable<System.DateTime> FechaContabilizacionDocumento { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string IdTiempoRegistroPadre { get; set; }
        public Nullable<int> IdRegistroPadre { get; set; }
        public Nullable<int> AnoEjercicioPadre { get; set; }
        public bool Sync { get; set; }
        public Nullable<System.DateTime> FechaCargaErp { get; set; }
    }
}
