//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlConsumo.Service.Models.ControlConsumo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public byte ID { get; set; }
        public string Description { get; set; }
        public string Etiqueta { get; set; }
        public int Inicio { get; set; }
        public int Fin { get; set; }
        public int MinutosInicio { get; set; }
        public int MinutosFin { get; set; }
        public string Empaque { get; set; }
    }
}
