#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ControlConsumo.Droid.Resource", IsApplication=true)]

namespace ControlConsumo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int MinutosCambio = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MinutosTurno = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080008
			public const int bg_app = 2131230728;
			
			// aapt resource value: 0x7f080017
			public const int black_d1 = 2131230743;
			
			// aapt resource value: 0x7f08000d
			public const int blue_base = 2131230733;
			
			// aapt resource value: 0x7f080015
			public const int blue_base_translucent = 2131230741;
			
			// aapt resource value: 0x7f080009
			public const int blue_dark = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int color_de_prueba_mamey = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int dark_gray = 2131230721;
			
			// aapt resource value: 0x7f08000e
			public const int gray_base = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int gray_bg_base = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int gray_dark = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int gray_light_d1 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int gray_light_d2 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int gray_light_d3 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int gray_super_light = 2131230740;
			
			// aapt resource value: 0x7f08001d
			public const int green_light = 2131230749;
			
			// aapt resource value: 0x7f080016
			public const int input_text = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int light_blue = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int light_gray = 2131230722;
			
			// aapt resource value: 0x7f08000a
			public const int orange_base = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int orange_base_c1 = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int orange_base_d1 = 2131230731;
			
			// aapt resource value: 0x7f08001e
			public const int red_dark = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int red_light = 2131230747;
			
			// aapt resource value: 0x7f080021
			public const int report_blue = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int report_green = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int report_yellow = 2131230752;
			
			// aapt resource value: 0x7f080018
			public const int status_pending = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int status_processed = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int status_rejected = 2131230746;
			
			// aapt resource value: 0x7f080004
			public const int text_color_column = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int white = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int white_pale_background = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int yellow = 2131230727;
			
			// aapt resource value: 0x7f08001c
			public const int yellow_light = 2131230748;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int activity_horizontal_margin = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int activity_vertical_margin = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int controls_radio = 2131034117;
			
			// aapt resource value: 0x7f05003d
			public const int dp_0 = 2131034173;
			
			// aapt resource value: 0x7f05003c
			public const int dp_1 = 2131034172;
			
			// aapt resource value: 0x7f050035
			public const int dp_10 = 2131034165;
			
			// aapt resource value: 0x7f05001b
			public const int dp_100 = 2131034139;
			
			// aapt resource value: 0x7f050007
			public const int dp_1000 = 2131034119;
			
			// aapt resource value: 0x7f050034
			public const int dp_12 = 2131034164;
			
			// aapt resource value: 0x7f050006
			public const int dp_1200 = 2131034118;
			
			// aapt resource value: 0x7f05001a
			public const int dp_125 = 2131034138;
			
			// aapt resource value: 0x7f050033
			public const int dp_13 = 2131034163;
			
			// aapt resource value: 0x7f050019
			public const int dp_130 = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int dp_140 = 2131034136;
			
			// aapt resource value: 0x7f050032
			public const int dp_15 = 2131034162;
			
			// aapt resource value: 0x7f050017
			public const int dp_150 = 2131034135;
			
			// aapt resource value: 0x7f050031
			public const int dp_16 = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int dp_18 = 2131034160;
			
			// aapt resource value: 0x7f050016
			public const int dp_180 = 2131034134;
			
			// aapt resource value: 0x7f05003b
			public const int dp_2 = 2131034171;
			
			// aapt resource value: 0x7f05002f
			public const int dp_20 = 2131034159;
			
			// aapt resource value: 0x7f050015
			public const int dp_200 = 2131034133;
			
			// aapt resource value: 0x7f05002e
			public const int dp_24 = 2131034158;
			
			// aapt resource value: 0x7f050014
			public const int dp_240 = 2131034132;
			
			// aapt resource value: 0x7f05002d
			public const int dp_25 = 2131034157;
			
			// aapt resource value: 0x7f050013
			public const int dp_250 = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int dp_280 = 2131034130;
			
			// aapt resource value: 0x7f05003a
			public const int dp_3 = 2131034170;
			
			// aapt resource value: 0x7f05002c
			public const int dp_30 = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int dp_32 = 2131034155;
			
			// aapt resource value: 0x7f050011
			public const int dp_320 = 2131034129;
			
			// aapt resource value: 0x7f05002a
			public const int dp_35 = 2131034154;
			
			// aapt resource value: 0x7f050010
			public const int dp_360 = 2131034128;
			
			// aapt resource value: 0x7f050029
			public const int dp_38 = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int dp_39 = 2131034152;
			
			// aapt resource value: 0x7f050039
			public const int dp_4 = 2131034169;
			
			// aapt resource value: 0x7f050027
			public const int dp_40 = 2131034151;
			
			// aapt resource value: 0x7f05000f
			public const int dp_400 = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int dp_420 = 2131034126;
			
			// aapt resource value: 0x7f050026
			public const int dp_45 = 2131034150;
			
			// aapt resource value: 0x7f05000d
			public const int dp_450 = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int dp_470 = 2131034124;
			
			// aapt resource value: 0x7f050025
			public const int dp_48 = 2131034149;
			
			// aapt resource value: 0x7f050038
			public const int dp_5 = 2131034168;
			
			// aapt resource value: 0x7f050024
			public const int dp_50 = 2131034148;
			
			// aapt resource value: 0x7f05000b
			public const int dp_500 = 2131034123;
			
			// aapt resource value: 0x7f050023
			public const int dp_54 = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int dp_55 = 2131034146;
			
			// aapt resource value: 0x7f050037
			public const int dp_6 = 2131034167;
			
			// aapt resource value: 0x7f050021
			public const int dp_60 = 2131034145;
			
			// aapt resource value: 0x7f05000a
			public const int dp_600 = 2131034122;
			
			// aapt resource value: 0x7f050020
			public const int dp_64 = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int dp_65 = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int dp_70 = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int dp_75 = 2131034141;
			
			// aapt resource value: 0x7f050009
			public const int dp_750 = 2131034121;
			
			// aapt resource value: 0x7f050036
			public const int dp_8 = 2131034166;
			
			// aapt resource value: 0x7f05001c
			public const int dp_80 = 2131034140;
			
			// aapt resource value: 0x7f050008
			public const int dp_850 = 2131034120;
			
			// aapt resource value: 0x7f05003e
			public const int dp_less_35 = 2131034174;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int item_touch_helper_swipe_escape_velocity = 2131034114;
			
			// aapt resource value: 0x7f050043
			public const int sp_10 = 2131034179;
			
			// aapt resource value: 0x7f050042
			public const int sp_12 = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int sp_15 = 2131034177;
			
			// aapt resource value: 0x7f050040
			public const int sp_20 = 2131034176;
			
			// aapt resource value: 0x7f05003f
			public const int sp_25 = 2131034175;
			
			// aapt resource value: 0x7f050044
			public const int sp_8 = 2131034180;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_budget = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_button_blue_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_button_orange_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_button_orange_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg_button_orange_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_input_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_input_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_input_gray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_input_gray_blue = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_input_gray_green = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg_input_gray_yellow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg_input_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bg_input_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bg_pick = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bg_spinner_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bg_spinner_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bg_spinner_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bg_spinner_white = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int drawer_shadow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int grid_element_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int grid_element_selected = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_back = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_action_search = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_bluetooth_connect = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_bom_report = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_box_product = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_calendar = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_cancel = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_cart_yellow = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_clock = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_diametro = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_drawer = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_entrada = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_litte_car = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_logout = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_minus = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_no_connections = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_ok = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_peso = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_plus = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_printer = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_printer_configured = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_printer_error = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_printer_working = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_production = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_salida = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_search = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_search_big = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_settings = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_ticket = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Icon = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Logo = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int LogoBlanco = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int progressbar = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int selector_button_blue = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int selector_button_orange = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int selector_input_text = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int selector_normal_list = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int selector_spinner = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int separator_vertical = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int whitecircle = 2130837564;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0600f1
			public const int ButtonAccept = 2131099889;
			
			// aapt resource value: 0x7f06009b
			public const int DrawerIcon = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int DrawerTitle = 2131099804;
			
			// aapt resource value: 0x7f060012
			public const int EditCantidad = 2131099666;
			
			// aapt resource value: 0x7f0600ef
			public const int EditPassword = 2131099887;
			
			// aapt resource value: 0x7f06006e
			public const int EditUpcCode = 2131099758;
			
			// aapt resource value: 0x7f0600ee
			public const int EditUserName = 2131099886;
			
			// aapt resource value: 0x7f060095
			public const int EditUserNameFull = 2131099797;
			
			// aapt resource value: 0x7f0600d5
			public const int ImgLogo = 2131099861;
			
			// aapt resource value: 0x7f060028
			public const int LinearLayoutPosition = 2131099688;
			
			// aapt resource value: 0x7f06009e
			public const int ListConfig = 2131099806;
			
			// aapt resource value: 0x7f0600e4
			public const int ListStock = 2131099876;
			
			// aapt resource value: 0x7f060119
			public const int Menu_A_delete = 2131099929;
			
			// aapt resource value: 0x7f06011a
			public const int Menu_A_edit = 2131099930;
			
			// aapt resource value: 0x7f0600f3
			public const int MyButton = 2131099891;
			
			// aapt resource value: 0x7f0600f0
			public const int Process = 2131099888;
			
			// aapt resource value: 0x7f06007a
			public const int RadioBuffer = 2131099770;
			
			// aapt resource value: 0x7f060079
			public const int RadioEquipo = 2131099769;
			
			// aapt resource value: 0x7f06007b
			public const int RadioInventario = 2131099771;
			
			// aapt resource value: 0x7f06005f
			public const int SwtInputOutput = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int SwtPartialElaborate = 2131099744;
			
			// aapt resource value: 0x7f06005d
			public const int SwtPlanification = 2131099741;
			
			// aapt resource value: 0x7f06000e
			public const int SwtStatus = 2131099662;
			
			// aapt resource value: 0x7f060111
			public const int TableSync = 2131099921;
			
			// aapt resource value: 0x7f060082
			public const int TxtViewGeneral = 2131099778;
			
			// aapt resource value: 0x7f060086
			public const int btnAccept = 2131099782;
			
			// aapt resource value: 0x7f060076
			public const int btnAcept = 2131099766;
			
			// aapt resource value: 0x7f060066
			public const int btnAceptDialog = 2131099750;
			
			// aapt resource value: 0x7f06008c
			public const int btnAceptDialog1 = 2131099788;
			
			// aapt resource value: 0x7f060081
			public const int btnAceptDialog2 = 2131099777;
			
			// aapt resource value: 0x7f06008d
			public const int btnAceptDialog3 = 2131099789;
			
			// aapt resource value: 0x7f06006d
			public const int btnAceptar = 2131099757;
			
			// aapt resource value: 0x7f0600c9
			public const int btnAceptarGeneral = 2131099849;
			
			// aapt resource value: 0x7f060084
			public const int btnBackDialog = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int btnCancel = 2131099781;
			
			// aapt resource value: 0x7f060087
			public const int btnCancel2 = 2131099783;
			
			// aapt resource value: 0x7f0600af
			public const int btnCancelActivate = 2131099823;
			
			// aapt resource value: 0x7f060067
			public const int btnCancelDialog = 2131099751;
			
			// aapt resource value: 0x7f06008e
			public const int btnCancelDialog2 = 2131099790;
			
			// aapt resource value: 0x7f060093
			public const int btnCancelDialog3 = 2131099795;
			
			// aapt resource value: 0x7f0600d1
			public const int btnCancelEntrada = 2131099857;
			
			// aapt resource value: 0x7f060098
			public const int btnCancelPrintConfirmationDialog = 2131099800;
			
			// aapt resource value: 0x7f0600eb
			public const int btnCancelSalida = 2131099883;
			
			// aapt resource value: 0x7f06006f
			public const int btnCancelar = 2131099759;
			
			// aapt resource value: 0x7f0600c0
			public const int btnConsultas = 2131099840;
			
			// aapt resource value: 0x7f060063
			public const int btnDate = 2131099747;
			
			// aapt resource value: 0x7f060101
			public const int btnDate1 = 2131099905;
			
			// aapt resource value: 0x7f060103
			public const int btnDate2 = 2131099907;
			
			// aapt resource value: 0x7f060112
			public const int btnDateMenu = 2131099922;
			
			// aapt resource value: 0x7f0600be
			public const int btnDesperdicios = 2131099838;
			
			// aapt resource value: 0x7f0600bd
			public const int btnEntrada = 2131099837;
			
			// aapt resource value: 0x7f06005a
			public const int btnFinPrinters = 2131099738;
			
			// aapt resource value: 0x7f0600bf
			public const int btnSalida = 2131099839;
			
			// aapt resource value: 0x7f0600a5
			public const int btnTime = 2131099813;
			
			// aapt resource value: 0x7f060105
			public const int btnTime1 = 2131099909;
			
			// aapt resource value: 0x7f060107
			public const int btnTime2 = 2131099911;
			
			// aapt resource value: 0x7f06001c
			public const int chkActivar = 2131099676;
			
			// aapt resource value: 0x7f06001a
			public const int chkEstado = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int chkNotificado = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int chkSelect = 2131099680;
			
			// aapt resource value: 0x7f0600fb
			public const int chkTurn1 = 2131099899;
			
			// aapt resource value: 0x7f0600fc
			public const int chkTurn2 = 2131099900;
			
			// aapt resource value: 0x7f0600fd
			public const int chkTurn3 = 2131099901;
			
			// aapt resource value: 0x7f060068
			public const int custom_dialog_first_rl = 2131099752;
			
			// aapt resource value: 0x7f0600f4
			public const int drawer_layout = 2131099892;
			
			// aapt resource value: 0x7f0600ca
			public const int drawer_list = 2131099850;
			
			// aapt resource value: 0x7f06009a
			public const int editBandeja = 2131099802;
			
			// aapt resource value: 0x7f060090
			public const int editBoxNo = 2131099792;
			
			// aapt resource value: 0x7f060071
			public const int editCode = 2131099761;
			
			// aapt resource value: 0x7f060074
			public const int editConfigPass = 2131099764;
			
			// aapt resource value: 0x7f0600a4
			public const int editDate = 2131099812;
			
			// aapt resource value: 0x7f060073
			public const int editNewPass = 2131099763;
			
			// aapt resource value: 0x7f060072
			public const int editOldPass = 2131099762;
			
			// aapt resource value: 0x7f06006b
			public const int editPassword = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int editQuantity = 2131099756;
			
			// aapt resource value: 0x7f060092
			public const int editScan = 2131099794;
			
			// aapt resource value: 0x7f0600f6
			public const int editScanBandejas = 2131099894;
			
			// aapt resource value: 0x7f06006a
			public const int editScanCodigo = 2131099754;
			
			// aapt resource value: 0x7f0600cb
			public const int editScanEntrada = 2131099851;
			
			// aapt resource value: 0x7f060055
			public const int editScanEquipment = 2131099733;
			
			// aapt resource value: 0x7f0600e7
			public const int editScanSalida = 2131099879;
			
			// aapt resource value: 0x7f0600a6
			public const int editTime = 2131099814;
			
			// aapt resource value: 0x7f060094
			public const int editTrayCigarsQuantity = 2131099796;
			
			// aapt resource value: 0x7f0600aa
			public const int errorLayout = 2131099818;
			
			// aapt resource value: 0x7f0600d3
			public const int feedback_Progress = 2131099859;
			
			// aapt resource value: 0x7f0600f2
			public const int feedback_content = 2131099890;
			
			// aapt resource value: 0x7f0600d2
			public const int feedback_flipper = 2131099858;
			
			// aapt resource value: 0x7f0600d4
			public const int feedback_loading_text = 2131099860;
			
			// aapt resource value: 0x7f06007e
			public const int flipper_view = 2131099774;
			
			// aapt resource value: 0x7f060080
			public const int flipper_view_floor = 2131099776;
			
			// aapt resource value: 0x7f06008b
			public const int flipper_view_message = 2131099787;
			
			// aapt resource value: 0x7f0600c7
			public const int frmErrors = 2131099847;
			
			// aapt resource value: 0x7f0600dd
			public const int gridView = 2131099869;
			
			// aapt resource value: 0x7f0600ac
			public const int grid_element_description = 2131099820;
			
			// aapt resource value: 0x7f0600ab
			public const int grid_element_image = 2131099819;
			
			// aapt resource value: 0x7f06001f
			public const int imgButtonChangeAlmacenamiento = 2131099679;
			
			// aapt resource value: 0x7f060030
			public const int imgButtonPrint = 2131099696;
			
			// aapt resource value: 0x7f060044
			public const int imgHideOther = 2131099716;
			
			// aapt resource value: 0x7f06003a
			public const int imgLittleBox = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int imgLittleCar = 2131099705;
			
			// aapt resource value: 0x7f0600c6
			public const int imgNoConnection = 2131099846;
			
			// aapt resource value: 0x7f0600c5
			public const int imgPrinterStatus = 2131099845;
			
			// aapt resource value: 0x7f06003b
			public const int imgRelease = 2131099707;
			
			// aapt resource value: 0x7f060043
			public const int imgShowOther = 2131099715;
			
			// aapt resource value: 0x7f06002c
			public const int imgStatusCancel = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int imgStatusOK = 2131099691;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f0600df
			public const int layoutGraphics = 2131099871;
			
			// aapt resource value: 0x7f06005e
			public const int layoutInputOutputControl = 2131099742;
			
			// aapt resource value: 0x7f0600de
			public const int layoutPeso = 2131099870;
			
			// aapt resource value: 0x7f06005c
			public const int layoutPlanification = 2131099740;
			
			// aapt resource value: 0x7f0600a9
			public const int linearLayout1 = 2131099817;
			
			// aapt resource value: 0x7f060053
			public const int linearLayout2 = 2131099731;
			
			// aapt resource value: 0x7f0600a7
			public const int linearLayout3 = 2131099815;
			
			// aapt resource value: 0x7f0600b2
			public const int linearLayoutBandejasConsumidas = 2131099826;
			
			// aapt resource value: 0x7f0600b5
			public const int linearLayoutCigarrosConsumidos = 2131099829;
			
			// aapt resource value: 0x7f0600ba
			public const int linearLayoutEmpaque = 2131099834;
			
			// aapt resource value: 0x7f0600bc
			public const int linearLayoutSecuencia = 2131099836;
			
			// aapt resource value: 0x7f0600f8
			public const int listBandejas = 2131099896;
			
			// aapt resource value: 0x7f060051
			public const int listCierres = 2131099729;
			
			// aapt resource value: 0x7f0600ad
			public const int listConfigs = 2131099821;
			
			// aapt resource value: 0x7f0600ec
			public const int listDesperdicios = 2131099884;
			
			// aapt resource value: 0x7f06010c
			public const int listDevolucion = 2131099916;
			
			// aapt resource value: 0x7f0600fa
			public const int listView = 2131099898;
			
			// aapt resource value: 0x7f06010b
			public const int listView2 = 2131099915;
			
			// aapt resource value: 0x7f0600db
			public const int lstBomReport = 2131099867;
			
			// aapt resource value: 0x7f0600dc
			public const int lstConsumo = 2131099868;
			
			// aapt resource value: 0x7f06007f
			public const int lstCuadre = 2131099775;
			
			// aapt resource value: 0x7f060083
			public const int lstGeneral = 2131099779;
			
			// aapt resource value: 0x7f0600e2
			public const int lstProduccion = 2131099874;
			
			// aapt resource value: 0x7f0600f7
			public const int lstReceipt = 2131099895;
			
			// aapt resource value: 0x7f0600f9
			public const int lstVarillas = 2131099897;
			
			// aapt resource value: 0x7f060088
			public const int lstlots = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int lstlots1 = 2131099785;
			
			// aapt resource value: 0x7f0600b0
			public const int lyBodyCommon = 2131099824;
			
			// aapt resource value: 0x7f0600c1
			public const int lyHeader = 2131099841;
			
			// aapt resource value: 0x7f060118
			public const int menu_Add = 2131099928;
			
			// aapt resource value: 0x7f060117
			public const int menu_Cancel = 2131099927;
			
			// aapt resource value: 0x7f060115
			public const int menu_Filter_date = 2131099925;
			
			// aapt resource value: 0x7f060116
			public const int menu_Filter_types = 2131099926;
			
			// aapt resource value: 0x7f06011b
			public const int menu_Fix = 2131099931;
			
			// aapt resource value: 0x7f060120
			public const int menu_Print = 2131099936;
			
			// aapt resource value: 0x7f060121
			public const int menu_Update = 2131099937;
			
			// aapt resource value: 0x7f060114
			public const int menu_action_search = 2131099924;
			
			// aapt resource value: 0x7f06011c
			public const int menu_back = 2131099932;
			
			// aapt resource value: 0x7f06011e
			public const int menu_diametro = 2131099934;
			
			// aapt resource value: 0x7f06011d
			public const int menu_peso = 2131099933;
			
			// aapt resource value: 0x7f06011f
			public const int menu_tiro = 2131099935;
			
			// aapt resource value: 0x7f060122
			public const int menu_user = 2131099938;
			
			// aapt resource value: 0x7f0600e0
			public const int plotView = 2131099872;
			
			// aapt resource value: 0x7f0600e1
			public const int plotView2 = 2131099873;
			
			// aapt resource value: 0x7f060110
			public const int progressBarSyncing = 2131099920;
			
			// aapt resource value: 0x7f060058
			public const int rbBluetooth = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int rbUsb = 2131099737;
			
			// aapt resource value: 0x7f060097
			public const int rgCantidadImpresiones = 2131099799;
			
			// aapt resource value: 0x7f060078
			public const int rgChoose = 2131099768;
			
			// aapt resource value: 0x7f060057
			public const int rgSelection = 2131099735;
			
			// aapt resource value: 0x7f06000d
			public const int spnArea = 2131099661;
			
			// aapt resource value: 0x7f0600ff
			public const int spnBatchID = 2131099903;
			
			// aapt resource value: 0x7f060065
			public const int spnEquipment = 2131099749;
			
			// aapt resource value: 0x7f060077
			public const int spnFecha = 2131099767;
			
			// aapt resource value: 0x7f0600a2
			public const int spnMaterial = 2131099810;
			
			// aapt resource value: 0x7f060096
			public const int spnMotivoReimpresion = 2131099798;
			
			// aapt resource value: 0x7f060061
			public const int spnProduct = 2131099745;
			
			// aapt resource value: 0x7f0600fe
			public const int spnProducto = 2131099902;
			
			// aapt resource value: 0x7f060056
			public const int spnSubEquipment = 2131099734;
			
			// aapt resource value: 0x7f0600a8
			public const int spnTiempo = 2131099816;
			
			// aapt resource value: 0x7f060064
			public const int spnTurn = 2131099748;
			
			// aapt resource value: 0x7f0600a3
			public const int spnVersion = 2131099811;
			
			// aapt resource value: 0x7f06010f
			public const int text1 = 2131099919;
			
			// aapt resource value: 0x7f06004f
			public const int txtBandeja = 2131099727;
			
			// aapt resource value: 0x7f0600cc
			public const int txtCodeEntrada = 2131099852;
			
			// aapt resource value: 0x7f06000a
			public const int txtCodigo = 2131099658;
			
			// aapt resource value: 0x7f0600b4
			public const int txtContadorBandejasConsumidas = 2131099828;
			
			// aapt resource value: 0x7f0600b7
			public const int txtContadorCigarrosConsumidos = 2131099831;
			
			// aapt resource value: 0x7f060007
			public const int txtDate = 2131099655;
			
			// aapt resource value: 0x7f060113
			public const int txtDateMenu = 2131099923;
			
			// aapt resource value: 0x7f0600a1
			public const int txtEquipment = 2131099809;
			
			// aapt resource value: 0x7f0600a0
			public const int txtEquipmentID = 2131099808;
			
			// aapt resource value: 0x7f060005
			public const int txtMaterial = 2131099653;
			
			// aapt resource value: 0x7f060050
			public const int txtMaterialBandeja = 2131099728;
			
			// aapt resource value: 0x7f0600c8
			public const int txtMessages = 2131099848;
			
			// aapt resource value: 0x7f06000b
			public const int txtName = 2131099659;
			
			// aapt resource value: 0x7f0600f5
			public const int txtQuestion = 2131099893;
			
			// aapt resource value: 0x7f0600b3
			public const int txtReportTitleContadorBandejasConsumidas = 2131099827;
			
			// aapt resource value: 0x7f0600b6
			public const int txtReportTitleContadorCantidadCigarros = 2131099830;
			
			// aapt resource value: 0x7f06004e
			public const int txtSecuencia = 2131099726;
			
			// aapt resource value: 0x7f06000c
			public const int txtShort = 2131099660;
			
			// aapt resource value: 0x7f06008a
			public const int txtShowMessages = 2131099786;
			
			// aapt resource value: 0x7f060091
			public const int txtShowMessagesBox = 2131099793;
			
			// aapt resource value: 0x7f060009
			public const int txtStatus = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int txtSubEquipment = 2131099656;
			
			// aapt resource value: 0x7f06001e
			public const int txtTime = 2131099678;
			
			// aapt resource value: 0x7f060006
			public const int txtVersion = 2131099654;
			
			// aapt resource value: 0x7f0600b1
			public const int txtViewAlmacenamiento = 2131099825;
			
			// aapt resource value: 0x7f06002d
			public const int txtViewAlmacenamiento_Filler = 2131099693;
			
			// aapt resource value: 0x7f060024
			public const int txtViewBandeja = 2131099684;
			
			// aapt resource value: 0x7f060035
			public const int txtViewBandejaConsumo = 2131099701;
			
			// aapt resource value: 0x7f0600e8
			public const int txtViewBandejaLabel = 2131099880;
			
			// aapt resource value: 0x7f060033
			public const int txtViewBandejas = 2131099699;
			
			// aapt resource value: 0x7f0600cf
			public const int txtViewBatch = 2131099855;
			
			// aapt resource value: 0x7f060037
			public const int txtViewBatchID = 2131099703;
			
			// aapt resource value: 0x7f0600b9
			public const int txtViewBatchIDLabel = 2131099833;
			
			// aapt resource value: 0x7f0600d0
			public const int txtViewBatchSap = 2131099856;
			
			// aapt resource value: 0x7f06008f
			public const int txtViewBoxMessage = 2131099791;
			
			// aapt resource value: 0x7f060048
			public const int txtViewBoxNumber = 2131099720;
			
			// aapt resource value: 0x7f060010
			public const int txtViewCaja = 2131099664;
			
			// aapt resource value: 0x7f060042
			public const int txtViewCajaNo = 2131099714;
			
			// aapt resource value: 0x7f060014
			public const int txtViewCantidad = 2131099668;
			
			// aapt resource value: 0x7f0600ce
			public const int txtViewCantidadEntrada = 2131099854;
			
			// aapt resource value: 0x7f06002a
			public const int txtViewCantidadFisico = 2131099690;
			
			// aapt resource value: 0x7f060029
			public const int txtViewCantidadLogico = 2131099689;
			
			// aapt resource value: 0x7f0600e9
			public const int txtViewCantidadSalida = 2131099881;
			
			// aapt resource value: 0x7f0600c2
			public const int txtViewCenter = 2131099842;
			
			// aapt resource value: 0x7f060031
			public const int txtViewCode = 2131099697;
			
			// aapt resource value: 0x7f060001
			public const int txtViewCodeBOM = 2131099649;
			
			// aapt resource value: 0x7f06004c
			public const int txtViewConsumido = 2131099724;
			
			// aapt resource value: 0x7f060062
			public const int txtViewDate = 2131099746;
			
			// aapt resource value: 0x7f060040
			public const int txtViewDescripcion = 2131099712;
			
			// aapt resource value: 0x7f0600cd
			public const int txtViewDescripcionEntrada = 2131099853;
			
			// aapt resource value: 0x7f06002e
			public const int txtViewEmpaque = 2131099694;
			
			// aapt resource value: 0x7f06004b
			public const int txtViewEntregado = 2131099723;
			
			// aapt resource value: 0x7f060046
			public const int txtViewEquipment = 2131099718;
			
			// aapt resource value: 0x7f06003c
			public const int txtViewEquipo = 2131099708;
			
			// aapt resource value: 0x7f0600d9
			public const int txtViewFCode = 2131099865;
			
			// aapt resource value: 0x7f060015
			public const int txtViewFecha = 2131099669;
			
			// aapt resource value: 0x7f06003d
			public const int txtViewFecha1 = 2131099709;
			
			// aapt resource value: 0x7f060100
			public const int txtViewFechaFrom = 2131099904;
			
			// aapt resource value: 0x7f060102
			public const int txtViewFechaTo = 2131099906;
			
			// aapt resource value: 0x7f06004d
			public const int txtViewFinal = 2131099725;
			
			// aapt resource value: 0x7f060108
			public const int txtViewFull = 2131099912;
			
			// aapt resource value: 0x7f06007c
			public const int txtViewHeader = 2131099772;
			
			// aapt resource value: 0x7f06003f
			public const int txtViewHeaderDetail = 2131099711;
			
			// aapt resource value: 0x7f060022
			public const int txtViewHora = 2131099682;
			
			// aapt resource value: 0x7f06003e
			public const int txtViewHora1 = 2131099710;
			
			// aapt resource value: 0x7f060017
			public const int txtViewHoraB = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int txtViewHoraE = 2131099672;
			
			// aapt resource value: 0x7f060104
			public const int txtViewHoraFrom = 2131099908;
			
			// aapt resource value: 0x7f060106
			public const int txtViewHoraTo = 2131099910;
			
			// aapt resource value: 0x7f060109
			public const int txtViewInEquipment = 2131099913;
			
			// aapt resource value: 0x7f060025
			public const int txtViewLogon = 2131099685;
			
			// aapt resource value: 0x7f060032
			public const int txtViewLote = 2131099698;
			
			// aapt resource value: 0x7f060011
			public const int txtViewLoteSap = 2131099665;
			
			// aapt resource value: 0x7f060026
			public const int txtViewLoteSup = 2131099686;
			
			// aapt resource value: 0x7f060041
			public const int txtViewLoteSupl = 2131099713;
			
			// aapt resource value: 0x7f06000f
			public const int txtViewMaterial = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int txtViewMaterialBOM = 2131099650;
			
			// aapt resource value: 0x7f060069
			public const int txtViewMessage = 2131099753;
			
			// aapt resource value: 0x7f060099
			public const int txtViewMessageScan = 2131099801;
			
			// aapt resource value: 0x7f0600ae
			public const int txtViewMessagesActivation = 2131099822;
			
			// aapt resource value: 0x7f0600d7
			public const int txtViewNoConfig = 2131099863;
			
			// aapt resource value: 0x7f0600d6
			public const int txtViewNoEquipment = 2131099862;
			
			// aapt resource value: 0x7f0600bb
			public const int txtViewPackageID = 2131099835;
			
			// aapt resource value: 0x7f060038
			public const int txtViewPeso = 2131099704;
			
			// aapt resource value: 0x7f06005b
			public const int txtViewPrinter = 2131099739;
			
			// aapt resource value: 0x7f0600c3
			public const int txtViewProcess = 2131099843;
			
			// aapt resource value: 0x7f060036
			public const int txtViewProduccion = 2131099702;
			
			// aapt resource value: 0x7f06007d
			public const int txtViewProduccionDate = 2131099773;
			
			// aapt resource value: 0x7f060021
			public const int txtViewProduct = 2131099681;
			
			// aapt resource value: 0x7f060019
			public const int txtViewProducto = 2131099673;
			
			// aapt resource value: 0x7f060052
			public const int txtViewProductoLarge = 2131099730;
			
			// aapt resource value: 0x7f0600d8
			public const int txtViewProductoLargeBOM = 2131099864;
			
			// aapt resource value: 0x7f0600b8
			public const int txtViewProductoShort = 2131099832;
			
			// aapt resource value: 0x7f0600da
			public const int txtViewProductoShortBOM = 2131099866;
			
			// aapt resource value: 0x7f06004a
			public const int txtViewReason = 2131099722;
			
			// aapt resource value: 0x7f06010a
			public const int txtViewRelease = 2131099914;
			
			// aapt resource value: 0x7f06010e
			public const int txtViewReturnProductTitle = 2131099918;
			
			// aapt resource value: 0x7f06010d
			public const int txtViewReturnTitle = 2131099917;
			
			// aapt resource value: 0x7f0600e6
			public const int txtViewSalidaLabel = 2131099878;
			
			// aapt resource value: 0x7f0600e5
			public const int txtViewSalidaTitle = 2131099877;
			
			// aapt resource value: 0x7f06002f
			public const int txtViewSecuencia = 2131099695;
			
			// aapt resource value: 0x7f0600c4
			public const int txtViewServer = 2131099844;
			
			// aapt resource value: 0x7f060045
			public const int txtViewShort = 2131099717;
			
			// aapt resource value: 0x7f060003
			public const int txtViewSupCodeBOM = 2131099651;
			
			// aapt resource value: 0x7f060034
			public const int txtViewTitle = 2131099700;
			
			// aapt resource value: 0x7f060027
			public const int txtViewTotal = 2131099687;
			
			// aapt resource value: 0x7f060047
			public const int txtViewTraza = 2131099719;
			
			// aapt resource value: 0x7f060023
			public const int txtViewTurn = 2131099683;
			
			// aapt resource value: 0x7f060016
			public const int txtViewTurno = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int txtViewUnidad = 2131099667;
			
			// aapt resource value: 0x7f060004
			public const int txtViewUnidadBOM = 2131099652;
			
			// aapt resource value: 0x7f0600ea
			public const int txtViewUnidadSalida = 2131099882;
			
			// aapt resource value: 0x7f06001d
			public const int txtViewUnidadView = 2131099677;
			
			// aapt resource value: 0x7f060049
			public const int txtViewUser = 2131099721;
			
			// aapt resource value: 0x7f060070
			public const int txtViewUserName = 2131099760;
			
			// aapt resource value: 0x7f060054
			public const int txtViewVersion = 2131099732;
			
			// aapt resource value: 0x7f0600ed
			public const int txtViewWasteTitle = 2131099885;
			
			// aapt resource value: 0x7f06009f
			public const int txtempty = 2131099807;
			
			// aapt resource value: 0x7f06009d
			public const int viewFlipper = 2131099805;
			
			// aapt resource value: 0x7f0600e3
			public const int viewFlipperStock = 2131099875;
			
			// aapt resource value: 0x7f060075
			public const int viewflipper = 2131099765;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int adapter_bom_report = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int adapter_config_config = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int adapter_config_equipment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int adapter_cuadre = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int adapter_cuadre_view = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int adapter_next_configs = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int adapter_produccion = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int adapter_receipt = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int adapter_receipt_stock = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int adapter_report_consumo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int adapter_report_empaque_detail = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int adapter_report_lack_consumo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int adapter_report_produccion = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int adapter_report_produccion_detail = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int adapter_report_produccion_promedio = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int adapter_report_produccion_sap = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int adapter_report_ticket_detail = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int adapter_report_ticket_header = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int adapter_report_varilla_detail = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int adapter_return = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int adapter_stock_detail = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int adapter_stock_head = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int adapter_stock_resume = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int adapter_trays_release = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int adapter_varilla = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int adapter_waste = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int cierre_activity = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int ConfigActivity = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int dialog_authorize_partial_elaborate = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int dialog_catch_material = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int dialog_catch_password = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int dialog_catch_quantity = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int dialog_catch_upcCode = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int dialog_change_password = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int dialog_choose_date_turn = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int dialog_choose_receipt = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int dialog_choose_turn_date = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int dialog_cuadre = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int dialog_general_list = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int dialog_lack_material_list = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int dialog_lots = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int dialog_messages = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int dialog_print_confirmation = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int dialog_scan_bandeja = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int dialog_tipo_almacenamiento = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int dialog_update = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int entry_drawer_layout = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int equipment_activity = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int equipment_new_config = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int error_dialog_messages = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int grid_element = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int include_activate_config = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int include_body_common = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int include_choose_action = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int include_display_common = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int include_display_errors = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int include_drawer_left = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int include_entrada_materiales = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int include_feedback_view = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int include_logo_view = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int include_no_config = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int include_report_bill_of_material = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int include_report_entradas = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int include_report_operator = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int include_report_peso = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int include_report_salida = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int include_report_stock = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int include_salida_materiales = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int include_waste_capture = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int layout1 = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int LoginActivity = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int Main = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int Menu_Activity = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int quality_activity = 2130903113;
			
			// aapt resource value: 0x7f03004a
			public const int question_dialog = 2130903114;
			
			// aapt resource value: 0x7f03004b
			public const int receipt_activity = 2130903115;
			
			// aapt resource value: 0x7f03004c
			public const int release_trays_activity = 2130903116;
			
			// aapt resource value: 0x7f03004d
			public const int reporte_varillas_activity = 2130903117;
			
			// aapt resource value: 0x7f03004e
			public const int reports_general_activity = 2130903118;
			
			// aapt resource value: 0x7f03004f
			public const int return_activity = 2130903119;
			
			// aapt resource value: 0x7f030050
			public const int return_product_activity = 2130903120;
			
			// aapt resource value: 0x7f030051
			public const int spinner_custom_layout = 2130903121;
			
			// aapt resource value: 0x7f030052
			public const int SpinnerEquipments = 2130903122;
			
			// aapt resource value: 0x7f030053
			public const int SyncActivity = 2130903123;
			
			// aapt resource value: 0x7f030054
			public const int TextViewEquipments = 2130903124;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int ConfigMenu = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int ConfigMenuChild = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int ConfigMenuChildOnlyDisable = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int fixedMenu = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int GeneralMenu = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int menu_back = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int QualityMenu = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int ReturnMenu = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int SettingMenu = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int wate_menu = 2131427337;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090003
			public const int Accept = 2131296259;
			
			// aapt resource value: 0x7f09000f
			public const int Ajust = 2131296271;
			
			// aapt resource value: 0x7f0900ad
			public const int AlertChangeTurn = 2131296429;
			
			// aapt resource value: 0x7f0900b0
			public const int AlertChangeTurnChangeDialog = 2131296432;
			
			// aapt resource value: 0x7f0900af
			public const int AlertChangeTurnDialog = 2131296431;
			
			// aapt resource value: 0x7f0900ae
			public const int AlertChangeTurnNow = 2131296430;
			
			// aapt resource value: 0x7f0900bb
			public const int AlertDeperdicios = 2131296443;
			
			// aapt resource value: 0x7f0900b5
			public const int AlertDownloading = 2131296437;
			
			// aapt resource value: 0x7f0900bc
			public const int AlertEmptyCuadre = 2131296444;
			
			// aapt resource value: 0x7f0900c3
			public const int AlertErrorCommunicationInline = 2131296451;
			
			// aapt resource value: 0x7f0900b3
			public const int AlertErrorDialog = 2131296435;
			
			// aapt resource value: 0x7f0900b4
			public const int AlertErrorNoAvailable = 2131296436;
			
			// aapt resource value: 0x7f0900c2
			public const int AlertErrorNoWifi = 2131296450;
			
			// aapt resource value: 0x7f0900c1
			public const int AlertErrorServerDown = 2131296449;
			
			// aapt resource value: 0x7f0900c4
			public const int AlertErrorTrayAlreadyReaded = 2131296452;
			
			// aapt resource value: 0x7f0900ba
			public const int AlertLastTray = 2131296442;
			
			// aapt resource value: 0x7f0900b1
			public const int AlertNeedPower = 2131296433;
			
			// aapt resource value: 0x7f0900bd
			public const int AlertNewConfig = 2131296445;
			
			// aapt resource value: 0x7f0900b7
			public const int AlertNoConfig = 2131296439;
			
			// aapt resource value: 0x7f0900b6
			public const int AlertNoConnection = 2131296438;
			
			// aapt resource value: 0x7f0900b2
			public const int AlertNoPower = 2131296434;
			
			// aapt resource value: 0x7f0900c0
			public const int AlertPleaseWait = 2131296448;
			
			// aapt resource value: 0x7f0900bf
			public const int AlertPleaseWaitMaintance = 2131296447;
			
			// aapt resource value: 0x7f0900c5
			public const int AlertScanMessage = 2131296453;
			
			// aapt resource value: 0x7f0900c6
			public const int AlertScanMessageWrong = 2131296454;
			
			// aapt resource value: 0x7f0900b8
			public const int AlertSyncBegin = 2131296440;
			
			// aapt resource value: 0x7f0900b9
			public const int AlertSyncComplete = 2131296441;
			
			// aapt resource value: 0x7f0900be
			public const int AlertWait = 2131296446;
			
			// aapt resource value: 0x7f090000
			public const int ApplicationLabel = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int ApplicationName = 2131296257;
			
			// aapt resource value: 0x7f09000e
			public const int Autorize = 2131296270;
			
			// aapt resource value: 0x7f090006
			public const int Back = 2131296262;
			
			// aapt resource value: 0x7f090015
			public const int ButtonAcceptText = 2131296277;
			
			// aapt resource value: 0x7f090081
			public const int ButtonCancel = 2131296385;
			
			// aapt resource value: 0x7f090080
			public const int ButtonClean = 2131296384;
			
			// aapt resource value: 0x7f090002
			public const int Cancel = 2131296258;
			
			// aapt resource value: 0x7f09005e
			public const int Change = 2131296350;
			
			// aapt resource value: 0x7f090034
			public const int ChangeDate = 2131296308;
			
			// aapt resource value: 0x7f090061
			public const int ChangeEquipment = 2131296353;
			
			// aapt resource value: 0x7f090060
			public const int ChangeFecha = 2131296352;
			
			// aapt resource value: 0x7f09005f
			public const int ChangePlanificado = 2131296351;
			
			// aapt resource value: 0x7f090062
			public const int ChangeProducto = 2131296354;
			
			// aapt resource value: 0x7f090063
			public const int ChangeProductoNoNext = 2131296355;
			
			// aapt resource value: 0x7f090065
			public const int ChangeProductoSoon = 2131296357;
			
			// aapt resource value: 0x7f090069
			public const int ChangeProductoStoreCold = 2131296361;
			
			// aapt resource value: 0x7f090068
			public const int ChangeProductoStoreDry = 2131296360;
			
			// aapt resource value: 0x7f09006a
			public const int ChangeProductoStoreTitle = 2131296362;
			
			// aapt resource value: 0x7f090066
			public const int ChangeProductoWorking = 2131296358;
			
			// aapt resource value: 0x7f090064
			public const int ChangeProductoWrong = 2131296356;
			
			// aapt resource value: 0x7f090067
			public const int ChangeProductoWrongEquipment = 2131296359;
			
			// aapt resource value: 0x7f090035
			public const int ChangeTime = 2131296309;
			
			// aapt resource value: 0x7f09006f
			public const int ChooseConsultas = 2131296367;
			
			// aapt resource value: 0x7f09006e
			public const int ChooseDesperdicio = 2131296366;
			
			// aapt resource value: 0x7f09006c
			public const int ChooseEntrada = 2131296364;
			
			// aapt resource value: 0x7f09006b
			public const int ChooseProducto = 2131296363;
			
			// aapt resource value: 0x7f09006d
			public const int ChooseSalida = 2131296365;
			
			// aapt resource value: 0x7f090164
			public const int CloseProcess = 2131296612;
			
			// aapt resource value: 0x7f09011b
			public const int CloseResult = 2131296539;
			
			// aapt resource value: 0x7f09011a
			public const int CloseTitle = 2131296538;
			
			// aapt resource value: 0x7f090011
			public const int Continue = 2131296273;
			
			// aapt resource value: 0x7f090111
			public const int DialogCloseCuadre = 2131296529;
			
			// aapt resource value: 0x7f090112
			public const int DialogCloseCuadreProducts = 2131296530;
			
			// aapt resource value: 0x7f090114
			public const int DialogClosedCuadred = 2131296532;
			
			// aapt resource value: 0x7f0900db
			public const int DialogClosedNoMax = 2131296475;
			
			// aapt resource value: 0x7f090113
			public const int DialogNoMaterial = 2131296531;
			
			// aapt resource value: 0x7f090110
			public const int DialogOpenCuadre = 2131296528;
			
			// aapt resource value: 0x7f090022
			public const int DrawerChange = 2131296290;
			
			// aapt resource value: 0x7f09002e
			public const int DrawerChangeErrorMessage = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int DrawerChangeErrorMessageNoAvailable = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int DrawerChangeErrorNoconfig = 2131296304;
			
			// aapt resource value: 0x7f09002a
			public const int DrawerClose = 2131296298;
			
			// aapt resource value: 0x7f090024
			public const int DrawerConfig = 2131296292;
			
			// aapt resource value: 0x7f090020
			public const int DrawerOperacions = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int DrawerPlan = 2131296289;
			
			// aapt resource value: 0x7f090029
			public const int DrawerQuality = 2131296297;
			
			// aapt resource value: 0x7f09002d
			public const int DrawerQuit = 2131296301;
			
			// aapt resource value: 0x7f090028
			public const int DrawerReceipt = 2131296296;
			
			// aapt resource value: 0x7f090023
			public const int DrawerRelease = 2131296291;
			
			// aapt resource value: 0x7f090027
			public const int DrawerReport = 2131296295;
			
			// aapt resource value: 0x7f09002c
			public const int DrawerReports = 2131296300;
			
			// aapt resource value: 0x7f090025
			public const int DrawerReturn = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int DrawerReturnProduct = 2131296294;
			
			// aapt resource value: 0x7f09002b
			public const int DrawerTrayUpdate = 2131296299;
			
			// aapt resource value: 0x7f090018
			public const int EditPasswordHint = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int EditUserNameFullHint = 2131296279;
			
			// aapt resource value: 0x7f090016
			public const int EditUserNameHint = 2131296278;
			
			// aapt resource value: 0x7f090070
			public const int Entry = 2131296368;
			
			// aapt resource value: 0x7f090071
			public const int EntryBarCode = 2131296369;
			
			// aapt resource value: 0x7f090072
			public const int EntryBarCodeHit = 2131296370;
			
			// aapt resource value: 0x7f0900a0
			public const int EntryBoxNo = 2131296416;
			
			// aapt resource value: 0x7f0900a3
			public const int EntryBoxNoWrong = 2131296419;
			
			// aapt resource value: 0x7f0900a2
			public const int EntryBoxQuantity = 2131296418;
			
			// aapt resource value: 0x7f090079
			public const int EntryLote = 2131296377;
			
			// aapt resource value: 0x7f09007a
			public const int EntryLoteSap = 2131296378;
			
			// aapt resource value: 0x7f090073
			public const int EntryMaterial = 2131296371;
			
			// aapt resource value: 0x7f09007e
			public const int EntryMaterialAlreadyRead = 2131296382;
			
			// aapt resource value: 0x7f09007f
			public const int EntryMaterialAlreadyReturn = 2131296383;
			
			// aapt resource value: 0x7f090074
			public const int EntryMaterialCodeHit = 2131296372;
			
			// aapt resource value: 0x7f090075
			public const int EntryMaterialDescHit = 2131296373;
			
			// aapt resource value: 0x7f09007b
			public const int EntryMaterialNoAvailable = 2131296379;
			
			// aapt resource value: 0x7f09007c
			public const int EntryMaterialNoStock = 2131296380;
			
			// aapt resource value: 0x7f09007d
			public const int EntryMaterialNoStockBox = 2131296381;
			
			// aapt resource value: 0x7f090076
			public const int EntryMaterialQuantHit = 2131296374;
			
			// aapt resource value: 0x7f090078
			public const int EntryMaterialSecuenHit = 2131296376;
			
			// aapt resource value: 0x7f090077
			public const int EntryMaterialUnitHit = 2131296375;
			
			// aapt resource value: 0x7f0900a1
			public const int EntryPesoNo = 2131296417;
			
			// aapt resource value: 0x7f0900a4
			public const int EntryPesoNoWrong = 2131296420;
			
			// aapt resource value: 0x7f0900a5
			public const int EntryQuantityWrong = 2131296421;
			
			// aapt resource value: 0x7f090050
			public const int EquipmentAssign = 2131296336;
			
			// aapt resource value: 0x7f090053
			public const int EquipmentAssignHit = 2131296339;
			
			// aapt resource value: 0x7f090051
			public const int EquipmentAssignSub = 2131296337;
			
			// aapt resource value: 0x7f090052
			public const int EquipmentPlanification = 2131296338;
			
			// aapt resource value: 0x7f090055
			public const int EquipmentPrinter = 2131296341;
			
			// aapt resource value: 0x7f090057
			public const int EquipmentPrinterCopies = 2131296343;
			
			// aapt resource value: 0x7f090056
			public const int EquipmentPrinterFind = 2131296342;
			
			// aapt resource value: 0x7f090059
			public const int EquipmentPrinterFound = 2131296345;
			
			// aapt resource value: 0x7f090058
			public const int EquipmentPrinterTitle = 2131296344;
			
			// aapt resource value: 0x7f09005c
			public const int EquipmentReadUserCode = 2131296348;
			
			// aapt resource value: 0x7f090054
			public const int EquipmentScanHit = 2131296340;
			
			// aapt resource value: 0x7f09005b
			public const int EquipmentTitleUser = 2131296347;
			
			// aapt resource value: 0x7f09005a
			public const int EquipmentupdateError = 2131296346;
			
			// aapt resource value: 0x7f09001d
			public const int FeedBackExpired = 2131296285;
			
			// aapt resource value: 0x7f09001c
			public const int FeedBackLock = 2131296284;
			
			// aapt resource value: 0x7f090019
			public const int FeedBackLogin = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int FeedBackWrong = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int FeedBackWrongCode = 2131296283;
			
			// aapt resource value: 0x7f09005d
			public const int InputOutputControl = 2131296349;
			
			// aapt resource value: 0x7f09015e
			public const int MaterialPendingValid = 2131296606;
			
			// aapt resource value: 0x7f090031
			public const int MessageBandejasValidacion = 2131296305;
			
			// aapt resource value: 0x7f090085
			public const int MessageBoxValueEntry = 2131296389;
			
			// aapt resource value: 0x7f090159
			public const int MessageDate = 2131296601;
			
			// aapt resource value: 0x7f09008a
			public const int MessageEmptyTray = 2131296394;
			
			// aapt resource value: 0x7f09015a
			public const int MessageEquipment = 2131296602;
			
			// aapt resource value: 0x7f090089
			public const int MessageExistBoxNumber = 2131296393;
			
			// aapt resource value: 0x7f090084
			public const int MessageExpiredEntry = 2131296388;
			
			// aapt resource value: 0x7f090082
			public const int MessageGoodEntry = 2131296386;
			
			// aapt resource value: 0x7f09015c
			public const int MessageProduct = 2131296604;
			
			// aapt resource value: 0x7f09015b
			public const int MessageTurn = 2131296603;
			
			// aapt resource value: 0x7f09015d
			public const int MessageUpdateBandejas = 2131296605;
			
			// aapt resource value: 0x7f090083
			public const int MessageWrongEntry = 2131296387;
			
			// aapt resource value: 0x7f090087
			public const int MessageWrongEntryNoBatchExist = 2131296391;
			
			// aapt resource value: 0x7f090088
			public const int MessageWrongEntryNoBatchExistSecuence = 2131296392;
			
			// aapt resource value: 0x7f090086
			public const int MessageWrongEntryNoExist = 2131296390;
			
			// aapt resource value: 0x7f090005
			public const int No = 2131296261;
			
			// aapt resource value: 0x7f090014
			public const int NoConection = 2131296276;
			
			// aapt resource value: 0x7f09004f
			public const int NoConfigConfiguration = 2131296335;
			
			// aapt resource value: 0x7f09004e
			public const int NoConfigEquipment = 2131296334;
			
			// aapt resource value: 0x7f09000c
			public const int NoEquipment = 2131296268;
			
			// aapt resource value: 0x7f09008b
			public const int Out = 2131296395;
			
			// aapt resource value: 0x7f09008c
			public const int OutBarCode = 2131296396;
			
			// aapt resource value: 0x7f09008d
			public const int OutBarCode2 = 2131296397;
			
			// aapt resource value: 0x7f090097
			public const int OutBarCodeDialogLot = 2131296407;
			
			// aapt resource value: 0x7f090098
			public const int OutBarCodeDialogLotPrint = 2131296408;
			
			// aapt resource value: 0x7f090099
			public const int OutBarCodeDialogNoMaterial = 2131296409;
			
			// aapt resource value: 0x7f09009a
			public const int OutBarCodeDialogNoQuantity = 2131296410;
			
			// aapt resource value: 0x7f090096
			public const int OutBarCodeHit = 2131296406;
			
			// aapt resource value: 0x7f090092
			public const int OutBarCodeTotal = 2131296402;
			
			// aapt resource value: 0x7f090090
			public const int OutBarCodeValue = 2131296400;
			
			// aapt resource value: 0x7f090091
			public const int OutBarCodeValue2 = 2131296401;
			
			// aapt resource value: 0x7f09008f
			public const int OutBarCodeWrong = 2131296399;
			
			// aapt resource value: 0x7f09008e
			public const int OutBarSecuenceWrond = 2131296398;
			
			// aapt resource value: 0x7f09009b
			public const int OutEntryPrintTitle = 2131296411;
			
			// aapt resource value: 0x7f090093
			public const int OutGoodTray = 2131296403;
			
			// aapt resource value: 0x7f090094
			public const int OutGoodTray2 = 2131296404;
			
			// aapt resource value: 0x7f09009d
			public const int OutNoGoodBox = 2131296413;
			
			// aapt resource value: 0x7f09009e
			public const int OutNoGoodBox2 = 2131296414;
			
			// aapt resource value: 0x7f09009f
			public const int OutNoGoodBoxBack = 2131296415;
			
			// aapt resource value: 0x7f090168
			public const int OutPartialElaborate = 2131296616;
			
			// aapt resource value: 0x7f09009c
			public const int OutReturnProduct = 2131296412;
			
			// aapt resource value: 0x7f090095
			public const int OutWrongTray = 2131296405;
			
			// aapt resource value: 0x7f090165
			public const int PartialElaborate = 2131296613;
			
			// aapt resource value: 0x7f090166
			public const int PartialElaborateConfig = 2131296614;
			
			// aapt resource value: 0x7f090167
			public const int PartialElaborateLabel = 2131296615;
			
			// aapt resource value: 0x7f090010
			public const int Print = 2131296272;
			
			// aapt resource value: 0x7f090163
			public const int PrinterMessageConnectProblem = 2131296611;
			
			// aapt resource value: 0x7f090162
			public const int PrinterMessageNoPairing = 2131296610;
			
			// aapt resource value: 0x7f090138
			public const int ReceiptAjust = 2131296568;
			
			// aapt resource value: 0x7f090142
			public const int ReceiptAreadyReceipt = 2131296578;
			
			// aapt resource value: 0x7f090141
			public const int ReceiptAreadyReturned = 2131296577;
			
			// aapt resource value: 0x7f090140
			public const int ReceiptAreadyScanned = 2131296576;
			
			// aapt resource value: 0x7f090139
			public const int ReceiptClose = 2131296569;
			
			// aapt resource value: 0x7f090134
			public const int ReceiptConceptReceive = 2131296564;
			
			// aapt resource value: 0x7f09013e
			public const int ReceiptConfirm = 2131296574;
			
			// aapt resource value: 0x7f090135
			public const int ReceiptConsumption = 2131296565;
			
			// aapt resource value: 0x7f090131
			public const int ReceiptMessages = 2131296561;
			
			// aapt resource value: 0x7f090132
			public const int ReceiptMessages2 = 2131296562;
			
			// aapt resource value: 0x7f090133
			public const int ReceiptMessages3 = 2131296563;
			
			// aapt resource value: 0x7f09013f
			public const int ReceiptNoStock = 2131296575;
			
			// aapt resource value: 0x7f09013d
			public const int ReceiptPositionComplete = 2131296573;
			
			// aapt resource value: 0x7f090137
			public const int ReceiptRetiro = 2131296567;
			
			// aapt resource value: 0x7f090136
			public const int ReceiptReturn = 2131296566;
			
			// aapt resource value: 0x7f09012e
			public const int ReceiptTitle = 2131296558;
			
			// aapt resource value: 0x7f09012f
			public const int ReceiptTitle2 = 2131296559;
			
			// aapt resource value: 0x7f090130
			public const int ReceiptTitle3 = 2131296560;
			
			// aapt resource value: 0x7f09013b
			public const int ReceiptTypeBuffer = 2131296571;
			
			// aapt resource value: 0x7f09013a
			public const int ReceiptTypeEquipo = 2131296570;
			
			// aapt resource value: 0x7f09013c
			public const int ReceiptTypeStock = 2131296572;
			
			// aapt resource value: 0x7f09012d
			public const int ReceiptTypeTitle = 2131296557;
			
			// aapt resource value: 0x7f0900aa
			public const int ReleaseEntryAlreadyRelease = 2131296426;
			
			// aapt resource value: 0x7f0900a8
			public const int ReleaseEntryFinished = 2131296424;
			
			// aapt resource value: 0x7f0900a7
			public const int ReleaseEntryMessage = 2131296423;
			
			// aapt resource value: 0x7f0900a6
			public const int ReleaseEntryTitle = 2131296422;
			
			// aapt resource value: 0x7f0900ac
			public const int ReleaseEntryTotal = 2131296428;
			
			// aapt resource value: 0x7f0900a9
			public const int ReleaseEntryWrong = 2131296425;
			
			// aapt resource value: 0x7f0900ab
			public const int ReleaseMessageAlreadyRelease = 2131296427;
			
			// aapt resource value: 0x7f090146
			public const int ReportDiametroPromedio = 2131296582;
			
			// aapt resource value: 0x7f090147
			public const int ReportDiametroRango = 2131296583;
			
			// aapt resource value: 0x7f090151
			public const int ReportMessageDiametroDown = 2131296593;
			
			// aapt resource value: 0x7f09014f
			public const int ReportMessageDiametroDownOut = 2131296591;
			
			// aapt resource value: 0x7f090150
			public const int ReportMessageDiametroUp = 2131296592;
			
			// aapt resource value: 0x7f09014e
			public const int ReportMessageDiametroUpOut = 2131296590;
			
			// aapt resource value: 0x7f090154
			public const int ReportMessageOut = 2131296596;
			
			// aapt resource value: 0x7f09014d
			public const int ReportMessagePesoDown = 2131296589;
			
			// aapt resource value: 0x7f09014b
			public const int ReportMessagePesoDownOut = 2131296587;
			
			// aapt resource value: 0x7f09014c
			public const int ReportMessagePesoUp = 2131296588;
			
			// aapt resource value: 0x7f09014a
			public const int ReportMessagePesoUpOut = 2131296586;
			
			// aapt resource value: 0x7f090156
			public const int ReportMessageRangoDown = 2131296598;
			
			// aapt resource value: 0x7f090155
			public const int ReportMessageRangoUp = 2131296597;
			
			// aapt resource value: 0x7f090153
			public const int ReportMessageTiro = 2131296595;
			
			// aapt resource value: 0x7f090152
			public const int ReportMessageTiroOut = 2131296594;
			
			// aapt resource value: 0x7f090107
			public const int ReportNoInfo = 2131296519;
			
			// aapt resource value: 0x7f090143
			public const int ReportNoOperacion = 2131296579;
			
			// aapt resource value: 0x7f090144
			public const int ReportPesoPromedio = 2131296580;
			
			// aapt resource value: 0x7f090145
			public const int ReportPesoRango = 2131296581;
			
			// aapt resource value: 0x7f090148
			public const int ReportTiroPromedio = 2131296584;
			
			// aapt resource value: 0x7f090149
			public const int ReportTiroRango = 2131296585;
			
			// aapt resource value: 0x7f0900f2
			public const int ReportTitleActual = 2131296498;
			
			// aapt resource value: 0x7f0900cd
			public const int ReportTitleAcumulated = 2131296461;
			
			// aapt resource value: 0x7f0900d7
			public const int ReportTitleAlmacenamiento_Filler = 2131296471;
			
			// aapt resource value: 0x7f0900f9
			public const int ReportTitleAverageElaborates = 2131296505;
			
			// aapt resource value: 0x7f09010d
			public const int ReportTitleBOM = 2131296525;
			
			// aapt resource value: 0x7f0900f7
			public const int ReportTitleBalance = 2131296503;
			
			// aapt resource value: 0x7f0900da
			public const int ReportTitleBandeja = 2131296474;
			
			// aapt resource value: 0x7f0900d9
			public const int ReportTitleBandejas = 2131296473;
			
			// aapt resource value: 0x7f0900dc
			public const int ReportTitleBandejas2 = 2131296476;
			
			// aapt resource value: 0x7f0900fc
			public const int ReportTitleBatchID = 2131296508;
			
			// aapt resource value: 0x7f0900d0
			public const int ReportTitleCaja = 2131296464;
			
			// aapt resource value: 0x7f0900cc
			public const int ReportTitleCantidad = 2131296460;
			
			// aapt resource value: 0x7f0900ff
			public const int ReportTitleCodigoSupl = 2131296511;
			
			// aapt resource value: 0x7f0900fb
			public const int ReportTitleComponent = 2131296507;
			
			// aapt resource value: 0x7f0900ce
			public const int ReportTitleConsumed = 2131296462;
			
			// aapt resource value: 0x7f0900ee
			public const int ReportTitleConsumido = 2131296494;
			
			// aapt resource value: 0x7f0900c8
			public const int ReportTitleConsumo = 2131296456;
			
			// aapt resource value: 0x7f09010e
			public const int ReportTitleContadorBandejasConsumidas = 2131296526;
			
			// aapt resource value: 0x7f09010f
			public const int ReportTitleContadorCantidadCigarros = 2131296527;
			
			// aapt resource value: 0x7f0900f1
			public const int ReportTitleCounter = 2131296497;
			
			// aapt resource value: 0x7f090100
			public const int ReportTitleDescripcion = 2131296512;
			
			// aapt resource value: 0x7f0900e9
			public const int ReportTitleDiametro = 2131296489;
			
			// aapt resource value: 0x7f0900f4
			public const int ReportTitleDifference = 2131296500;
			
			// aapt resource value: 0x7f0900e7
			public const int ReportTitleEmpaque = 2131296487;
			
			// aapt resource value: 0x7f0900e0
			public const int ReportTitleEntrada = 2131296480;
			
			// aapt resource value: 0x7f0900ef
			public const int ReportTitleEntregado = 2131296495;
			
			// aapt resource value: 0x7f0900fd
			public const int ReportTitleEquipment = 2131296509;
			
			// aapt resource value: 0x7f0900d4
			public const int ReportTitleFecha = 2131296468;
			
			// aapt resource value: 0x7f0900d5
			public const int ReportTitleFechaSalida = 2131296469;
			
			// aapt resource value: 0x7f0900f0
			public const int ReportTitleFinal = 2131296496;
			
			// aapt resource value: 0x7f0900f6
			public const int ReportTitleFisico = 2131296502;
			
			// aapt resource value: 0x7f090109
			public const int ReportTitleFull = 2131296521;
			
			// aapt resource value: 0x7f0900d6
			public const int ReportTitleHora = 2131296470;
			
			// aapt resource value: 0x7f0900d8
			public const int ReportTitleHoraSalida = 2131296472;
			
			// aapt resource value: 0x7f09010a
			public const int ReportTitleInMaquine = 2131296522;
			
			// aapt resource value: 0x7f0900ec
			public const int ReportTitleInventory = 2131296492;
			
			// aapt resource value: 0x7f09010c
			public const int ReportTitleLocated = 2131296524;
			
			// aapt resource value: 0x7f0900d1
			public const int ReportTitleLote = 2131296465;
			
			// aapt resource value: 0x7f0900d2
			public const int ReportTitleLoteBacht = 2131296466;
			
			// aapt resource value: 0x7f0900d3
			public const int ReportTitleLoteSupl = 2131296467;
			
			// aapt resource value: 0x7f0900cb
			public const int ReportTitleMaterial = 2131296459;
			
			// aapt resource value: 0x7f090101
			public const int ReportTitleNoProductTraza = 2131296513;
			
			// aapt resource value: 0x7f0900e6
			public const int ReportTitlePeso = 2131296486;
			
			// aapt resource value: 0x7f0900c7
			public const int ReportTitleProduccion = 2131296455;
			
			// aapt resource value: 0x7f090102
			public const int ReportTitleProductionBandeja = 2131296514;
			
			// aapt resource value: 0x7f090108
			public const int ReportTitleProductionxBandeja = 2131296520;
			
			// aapt resource value: 0x7f0900c9
			public const int ReportTitleProducto = 2131296457;
			
			// aapt resource value: 0x7f0900ca
			public const int ReportTitleProductoShort = 2131296458;
			
			// aapt resource value: 0x7f0900e3
			public const int ReportTitleReason = 2131296483;
			
			// aapt resource value: 0x7f09010b
			public const int ReportTitleRelease = 2131296523;
			
			// aapt resource value: 0x7f0900e1
			public const int ReportTitleSalida = 2131296481;
			
			// aapt resource value: 0x7f0900e8
			public const int ReportTitleSecuence = 2131296488;
			
			// aapt resource value: 0x7f0900e5
			public const int ReportTitleStock = 2131296485;
			
			// aapt resource value: 0x7f0900ed
			public const int ReportTitleStockDetail = 2131296493;
			
			// aapt resource value: 0x7f0900f8
			public const int ReportTitleStockNow = 2131296504;
			
			// aapt resource value: 0x7f0900f5
			public const int ReportTitleTeorico = 2131296501;
			
			// aapt resource value: 0x7f0900fa
			public const int ReportTitleTicket = 2131296506;
			
			// aapt resource value: 0x7f0900ea
			public const int ReportTitleTiro = 2131296490;
			
			// aapt resource value: 0x7f0900df
			public const int ReportTitleTotal = 2131296479;
			
			// aapt resource value: 0x7f0900de
			public const int ReportTitleTotalProduccion = 2131296478;
			
			// aapt resource value: 0x7f0900fe
			public const int ReportTitleTraza = 2131296510;
			
			// aapt resource value: 0x7f0900e2
			public const int ReportTitleTurn = 2131296482;
			
			// aapt resource value: 0x7f090104
			public const int ReportTitleTurno1 = 2131296516;
			
			// aapt resource value: 0x7f090105
			public const int ReportTitleTurno2 = 2131296517;
			
			// aapt resource value: 0x7f090106
			public const int ReportTitleTurno3 = 2131296518;
			
			// aapt resource value: 0x7f090103
			public const int ReportTitleTurnos = 2131296515;
			
			// aapt resource value: 0x7f0900dd
			public const int ReportTitleUltimaCantidad = 2131296477;
			
			// aapt resource value: 0x7f0900cf
			public const int ReportTitleUnidad = 2131296463;
			
			// aapt resource value: 0x7f0900e4
			public const int ReportTitleUsuario = 2131296484;
			
			// aapt resource value: 0x7f0900f3
			public const int ReportTitleValidate = 2131296499;
			
			// aapt resource value: 0x7f0900eb
			public const int ReportTitleWrongQuantity = 2131296491;
			
			// aapt resource value: 0x7f090117
			public const int ReturnMessages = 2131296535;
			
			// aapt resource value: 0x7f090158
			public const int ReturnProductResult = 2131296600;
			
			// aapt resource value: 0x7f090157
			public const int ReturnProductTitle = 2131296599;
			
			// aapt resource value: 0x7f090115
			public const int ReturnTitle = 2131296533;
			
			// aapt resource value: 0x7f090116
			public const int ReturnTitleReprint = 2131296534;
			
			// aapt resource value: 0x7f090009
			public const int ScreenConfigurations = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int ScreenEquipments = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int ScreenMaterialIN = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int ScreenMaterialOut = 2131296267;
			
			// aapt resource value: 0x7f090007
			public const int ScreenOutServices = 2131296263;
			
			// aapt resource value: 0x7f090036
			public const int Select = 2131296310;
			
			// aapt resource value: 0x7f090039
			public const int Select_prompt_area = 2131296313;
			
			// aapt resource value: 0x7f090037
			public const int Select_prompt_subEquipment = 2131296311;
			
			// aapt resource value: 0x7f09000d
			public const int Turn = 2131296269;
			
			// aapt resource value: 0x7f09003a
			public const int UnSelect_prompt_area = 2131296314;
			
			// aapt resource value: 0x7f090038
			public const int UnSelect_prompt_subEquipment = 2131296312;
			
			// aapt resource value: 0x7f090032
			public const int UpdatingBandejaSql = 2131296306;
			
			// aapt resource value: 0x7f09011e
			public const int VarillaChooseTitle = 2131296542;
			
			// aapt resource value: 0x7f09011d
			public const int VarillaFecha = 2131296541;
			
			// aapt resource value: 0x7f090120
			public const int VarillaMessages = 2131296544;
			
			// aapt resource value: 0x7f09011f
			public const int VarillaTitle = 2131296543;
			
			// aapt resource value: 0x7f09011c
			public const int VarillaTurn = 2131296540;
			
			// aapt resource value: 0x7f090119
			public const int WastesMessages = 2131296537;
			
			// aapt resource value: 0x7f090118
			public const int WastesTitle = 2131296536;
			
			// aapt resource value: 0x7f090004
			public const int Yes = 2131296260;
			
			// aapt resource value: 0x7f09003b
			public const int action_equipment = 2131296315;
			
			// aapt resource value: 0x7f09003d
			public const int action_search_for = 2131296317;
			
			// aapt resource value: 0x7f09003c
			public const int action_seatch = 2131296316;
			
			// aapt resource value: 0x7f090160
			public const int all_component_complete = 2131296608;
			
			// aapt resource value: 0x7f09001f
			public const int closed_mode = 2131296287;
			
			// aapt resource value: 0x7f09003f
			public const int dialog_new_config = 2131296319;
			
			// aapt resource value: 0x7f090042
			public const int dialog_new_config_no_new = 2131296322;
			
			// aapt resource value: 0x7f090041
			public const int dialog_new_config_no_old = 2131296321;
			
			// aapt resource value: 0x7f090040
			public const int dialog_new_config_planchar = 2131296320;
			
			// aapt resource value: 0x7f090121
			public const int dialogpassTitle = 2131296545;
			
			// aapt resource value: 0x7f090125
			public const int dialogpasscode = 2131296549;
			
			// aapt resource value: 0x7f090124
			public const int dialogpassconfirm = 2131296548;
			
			// aapt resource value: 0x7f09012c
			public const int dialogpasscorrect = 2131296556;
			
			// aapt resource value: 0x7f090123
			public const int dialogpassnew = 2131296547;
			
			// aapt resource value: 0x7f09012b
			public const int dialogpassnocode = 2131296555;
			
			// aapt resource value: 0x7f090127
			public const int dialogpassnoempty = 2131296551;
			
			// aapt resource value: 0x7f09012a
			public const int dialogpassnoleght = 2131296554;
			
			// aapt resource value: 0x7f090128
			public const int dialogpassnoold = 2131296552;
			
			// aapt resource value: 0x7f090129
			public const int dialogpassnosamecode = 2131296553;
			
			// aapt resource value: 0x7f090122
			public const int dialogpassold = 2131296546;
			
			// aapt resource value: 0x7f090126
			public const int dialogpasswrongconfirm = 2131296550;
			
			// aapt resource value: 0x7f090044
			public const int menu_Deleted = 2131296324;
			
			// aapt resource value: 0x7f090045
			public const int menu_Edit = 2131296325;
			
			// aapt resource value: 0x7f090048
			public const int menu_Restart = 2131296328;
			
			// aapt resource value: 0x7f090046
			public const int menu_Save = 2131296326;
			
			// aapt resource value: 0x7f090047
			public const int menu_Update = 2131296327;
			
			// aapt resource value: 0x7f090049
			public const int menu_User = 2131296329;
			
			// aapt resource value: 0x7f09004c
			public const int menu_diametro = 2131296332;
			
			// aapt resource value: 0x7f09004b
			public const int menu_peso = 2131296331;
			
			// aapt resource value: 0x7f09004a
			public const int menu_print = 2131296330;
			
			// aapt resource value: 0x7f090043
			public const int menu_selected = 2131296323;
			
			// aapt resource value: 0x7f09004d
			public const int menu_tiro = 2131296333;
			
			// aapt resource value: 0x7f090161
			public const int need_new_tray = 2131296609;
			
			// aapt resource value: 0x7f090033
			public const int no_data = 2131296307;
			
			// aapt resource value: 0x7f09015f
			public const int no_out_posible = 2131296607;
			
			// aapt resource value: 0x7f09001e
			public const int open_mode = 2131296286;
			
			// aapt resource value: 0x7f090013
			public const int sync_permits = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int synchronizing = 2131296274;
			
			// aapt resource value: 0x7f09003e
			public const int update_config = 2131296318;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0002
			public const int ActionbarStyle = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int AppBaseTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int AppTheme = 2131361793;
			
			// aapt resource value: 0x7f0a0004
			public const int SubTitleTextStyle = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int TitleTextStyle = 2131361795;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
